import "./globals.css";
import { StrainContextProvider } from "./contexts/strain.context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StrainContextProvider>{children}</StrainContextProvider>
      </body>
    </html>
  );
}
